# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Control.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import RPi._GPIO as GPIO
import gpiozero

class Ui_MainWindow(object):
        def Initiate(self):
                GPIO.setwarnings(False)
                GPIO.setmode(GPIO.BCM)
                GPIO.setup(18, GPIO.OUT)
                GPIO.output(18, 0)

        def Deactivate(self):
                RELAY_PIN = 18
                relay = gpiozero.OutputDevice(RELAY_PIN,active_high=False,initial_value=False)
                relay.off()

        def Light_ON(self):
                GPIO.setwarnings(False)

                GPIO.setmode(GPIO.BCM)

                GPIO.setup(17, GPIO.OUT)

                GPIO.output(17, 0)

        def Light_OFF(self):
                RELAY_PIN = 17

                relay = gpiozero.OutputDevice(RELAY_PIN,active_high=False,initial_value=False)

                relay.off()

        def Blue_ON(self):
                GPIO.setwarnings(False)

                GPIO.setmode(GPIO.BCM)

                GPIO.setup(22, GPIO.OUT)

                GPIO.output(22, True)


        def Blue_OFF(self):
                GPIO.setwarnings(False)

                GPIO.setmode(GPIO.BCM)

                GPIO.setup(22, GPIO.OUT)

                GPIO.output(22, False)

        def Red_ON(self):
                GPIO.setwarnings(False)

                GPIO.setmode(GPIO.BCM)

                GPIO.setup(27, GPIO.OUT)

                GPIO.output(27, True)


        def Red_OFF(self):
                GPIO.setwarnings(False)

                GPIO.setmode(GPIO.BCM)

                GPIO.setup(27, GPIO.OUT)

                GPIO.output(27, False)

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(840, 447)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(-10, -20, 861, 601))
                self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
                self.label.setMouseTracking(False)
                self.label.setFocusPolicy(QtCore.Qt.NoFocus)
                self.label.setToolTipDuration(-1)
                self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
                self.label.setText("")
                self.label.setScaledContents(True)
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(40, 30, 191, 81))
                self.label_2.setStyleSheet("background-color: rgb(199, 68, 118);\n"
        "border-radius: 30px;")
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(20, 130, 251, 81))
                self.label_3.setStyleSheet("background-color: rgb(174, 55, 210);\n"
        "border-radius: 30px;")
                self.label_3.setObjectName("label_3")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.setGeometry(QtCore.QRect(50, 50, 171, 41))
                self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
                self.pushButton.setMouseTracking(False)
                self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
                self.pushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
                self.pushButton.setToolTipDuration(0)
                self.pushButton.setStyleSheet("border-radius:none;")
                self.pushButton.setText("")
                self.pushButton.setObjectName("pushButton")
                self.pushButton.clicked.connect(self.Initiate)
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.setGeometry(QtCore.QRect(40, 150, 201, 41))
                self.pushButton_2.setStyleSheet("border-radius:none;")
                self.pushButton_2.setText("")
                self.pushButton_2.setObjectName("pushButton_2")
                self.pushButton_2.clicked.connect(self.Deactivate)
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(330, 30, 141, 71))
                self.label_4.setStyleSheet("background-color: rgb(109, 59, 230);\n"
        "border-radius: 30px;")
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(330, 130, 141, 71))
                self.label_5.setStyleSheet("background-color: rgb(50, 45, 93);\n"
        "border-radius: 30px;")
                self.label_5.setObjectName("label_5")
                self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_3.setGeometry(QtCore.QRect(350, 40, 101, 51))
                self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
                self.pushButton_3.setMouseTracking(False)
                self.pushButton_3.setFocusPolicy(QtCore.Qt.ClickFocus)
                self.pushButton_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
                self.pushButton_3.setToolTipDuration(0)
                self.pushButton_3.setStyleSheet("border-radius:none;")
                self.pushButton_3.setText("")
                self.pushButton_3.setObjectName("pushButton_3")
                self.pushButton_3.clicked.connect(self.Light_ON)
                self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_4.setGeometry(QtCore.QRect(350, 140, 101, 51))
                self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
                self.pushButton_4.setMouseTracking(False)
                self.pushButton_4.setFocusPolicy(QtCore.Qt.ClickFocus)
                self.pushButton_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
                self.pushButton_4.setToolTipDuration(0)
                self.pushButton_4.setStyleSheet("border-radius:none;")
                self.pushButton_4.setText("")
                self.pushButton_4.setObjectName("pushButton_4")
                self.pushButton_4.clicked.connect(self.Light_OFF)
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(540, 30, 251, 81))
                self.label_6.setStyleSheet("background-color: rgb(24, 109, 227);\n"
        "border-radius: 30px;")
                self.label_6.setObjectName("label_6")
                self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_5.setGeometry(QtCore.QRect(566, 46, 201, 51))
                self.pushButton_5.setStyleSheet("border-radius:none;")
                self.pushButton_5.setText("")
                self.pushButton_5.setObjectName("pushButton_5")
                self.pushButton_5.clicked.connect(self.Blue_ON)
                self.label_7 = QtWidgets.QLabel(self.centralwidget)
                self.label_7.setGeometry(QtCore.QRect(540, 130, 251, 81))
                self.label_7.setStyleSheet("background-color: rgb(28, 20, 72);\n"
        "border-radius: 30px;")
                self.label_7.setObjectName("label_7")
                self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_6.setGeometry(QtCore.QRect(560, 146, 211, 51))
                self.pushButton_6.setStyleSheet("border-radius:none;")
                self.pushButton_6.setText("")
                self.pushButton_6.setObjectName("pushButton_6")
                self.pushButton_6.clicked.connect(self.Blue_OFF)
                self.label_8 = QtWidgets.QLabel(self.centralwidget)
                self.label_8.setGeometry(QtCore.QRect(290, 250, 251, 81))
                self.label_8.setStyleSheet("background-color: rgb(173, 27, 23);\n"
        "border-radius: 30px;")
                self.label_8.setObjectName("label_8")
                self.label_9 = QtWidgets.QLabel(self.centralwidget)
                self.label_9.setGeometry(QtCore.QRect(290, 350, 251, 81))
                self.label_9.setStyleSheet("background-color: rgb(131, 17, 17);\n"
        "border-radius: 30px;")
                self.label_9.setObjectName("label_9")
                self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_7.setGeometry(QtCore.QRect(310, 266, 211, 51))
                self.pushButton_7.setStyleSheet("border-radius:none;")
                self.pushButton_7.setText("")
                self.pushButton_7.setObjectName("pushButton_7")
                self.pushButton_7.clicked.connect(self.Red_ON)
                self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_8.setGeometry(QtCore.QRect(310, 366, 211, 51))
                self.pushButton_8.setStyleSheet("border-radius:none;")
                self.pushButton_8.setText("")
                self.pushButton_8.setObjectName("pushButton_8")
                self.pushButton_8.clicked.connect(self.Red_OFF)
                MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Initiate System</span></p></body></html>"))
                self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Deactivate System</span></p></body></html>"))
                self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Light ON</span></p></body></html>"))
                self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Light OFF</span></p></body></html>"))
                self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Arc Reactor Blue ON</span></p></body></html>"))
                self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Arc Reactor Blue OFF</span></p></body></html>"))
                self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Arc Reactor Red ON</span></p></body></html>"))
                self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Arc Reactor Red OFF</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
